version: "3.8"

services:
  onyx-psql-db:
    image: postgres
    container_name: onyx-psql-db
    restart: always
    environment:
      PGUSER: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: onyx-db
    ports:
      - "5432:5432"
    volumes:
      - onyx-psql-db-data:/var/lib/postgresql/data

  onyx-frontend: # Nom du container du frontend
    image: onyx-frontend-image
    container_name: onyx-frontend
    build:
      context: ./onyx-institut-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    # volumes:
    #   - onyx-frontend:/usr/local/app # Montage du code source local dans le conteneur
    depends_on:
      - onyx-psql-db

  onyx-backend:
    image: onyx-backend-image
    container_name: onyx-backend
    build:
      context: ./onyx-institut-backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - onyx-psql-db

volumes:
  onyx-psql-db-data:
  # onyx-frontend:
